In [12]:
import pandas as pd

In [8]:
df = pd.read_json('./big_nfl_data.json', orient='records')

In [9]:
df.head()

,player_id,year,game_id,date,game_number,age,team,game_location,opponent,game_won,...,defense_interception_yards,defense_interception_touchdowns,defense_safeties,point_after_attemps,point_after_makes,field_goal_attempts,field_goal_makes,punting_attempts,punting_yards,punting_blocked
0,4088,1992,199209130ram,1992-09-13,1,23.190,NWE,A,RAM,False,...,0,0,0,0,0,0,0,0,0,0
1,4088,1992,199209200nwe,1992-09-20,2,23.197,NWE,H,SEA,False,...,0,0,0,0,0,0,0,0,0,0
2,4088,1992,199209270nwe,1992-09-27,3,23.204,NWE,H,BUF,False,...,0,0,0,0,0,0,0,0,0,0
3,4088,1992,199210040nyj,1992-10-04,4,23.211,NWE,A,NYJ,False,...,0,0,0,0,0,0,0,0,0,0
4,4088,1992,199210110nwe,1992-10-11,5,23.218,NWE,H,SFO,False,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.columns

Index(['player_id', 'year', 'game_id', 'date', 'game_number', 'age', 'team',
       'game_location', 'opponent', 'game_won', 'player_team_score',
       'opponent_score', 'passing_attempts', 'passing_completions',
       'passing_yards', 'passing_rating', 'passing_touchdowns',
       'passing_interceptions', 'passing_sacks', 'passing_sacks_yards_lost',
       'rushing_attempts', 'rushing_yards', 'rushing_touchdowns',
       'receiving_targets', 'receiving_receptions', 'receiving_yards',
       'receiving_touchdowns', 'kick_return_attempts', 'kick_return_yards',
       'kick_return_touchdowns', 'punt_return_attempts', 'punt_return_yards',
       'punt_return_touchdowns', 'defense_sacks', 'defense_tackles',
       'defense_tackle_assists', 'defense_interceptions',
       'defense_interception_yards', 'defense_interception_touchdowns',
       'defense_safeties', 'point_after_attemps', 'point_after_makes',
       'field_goal_attempts', 'field_goal_makes', 'punting_attempts',
       'punting_yards', 'punting_blocked'],
      dtype='object')

where are the stats for two-point conversions