In [31]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_json('./big_nfl_data.json', orient='records')

In [19]:
df.head()

,player_id,year,game_id,date,game_number,age,team,game_location,opponent,game_won,...,defense_interception_yards,defense_interception_touchdowns,defense_safeties,point_after_attemps,point_after_makes,field_goal_attempts,field_goal_makes,punting_attempts,punting_yards,punting_blocked
0,4088,1992,199209130ram,1992-09-13,1,23.190,NWE,A,RAM,False,...,0,0,0,0,0,0,0,0,0,0
1,4088,1992,199209200nwe,1992-09-20,2,23.197,NWE,H,SEA,False,...,0,0,0,0,0,0,0,0,0,0
2,4088,1992,199209270nwe,1992-09-27,3,23.204,NWE,H,BUF,False,...,0,0,0,0,0,0,0,0,0,0
3,4088,1992,199210040nyj,1992-10-04,4,23.211,NWE,A,NYJ,False,...,0,0,0,0,0,0,0,0,0,0
4,4088,1992,199210110nwe,1992-10-11,5,23.218,NWE,H,SFO,False,...,0,0,0,0,0,0,0,0,0,0

where are the stats for two-point conversions

In [20]:
df.shape

(495410, 47)

In [21]:
df = df.loc[df["year"] > 1989]

In [22]:
offense_df = df.loc[(df["defense_sacks"] < 1) & (df["defense_tackles"] < 1) & (df["defense_tackle_assists"] < 1) & (df["defense_interceptions"] < 1) & (df["defense_interception_yards"] < 1) & (df["defense_interception_touchdowns"] < 1) & (df["defense_safeties"] < 1)]

In [23]:
offense_df

,player_id,year,game_id,date,game_number,age,team,game_location,opponent,game_won,...,defense_interception_yards,defense_interception_touchdowns,defense_safeties,point_after_attemps,point_after_makes,field_goal_attempts,field_goal_makes,punting_attempts,punting_yards,punting_blocked
0,4088,1992,199209130ram,1992-09-13,1,23.190,NWE,A,RAM,False,...,0,0,0,0,0,0,0,0,0,0
1,4088,1992,199209200nwe,1992-09-20,2,23.197,NWE,H,SEA,False,...,0,0,0,0,0,0,0,0,0,0
2,4088,1992,199209270nwe,1992-09-27,3,23.204,NWE,H,BUF,False,...,0,0,0,0,0,0,0,0,0,0
3,4088,1992,199210040nyj,1992-10-04,4,23.211,NWE,A,NYJ,False,...,0,0,0,0,0,0,0,0,0,0
4,4088,1992,199210110nwe,1992-10-11,5,23.218,NWE,H,SFO,False,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495385,916,2000,200011300min,2000-11-30,13,24.093,DET,A,MIN,False,...,0,0,0,0,0,0,0,0,0,0
495387,916,2000,200012170nyj,2000-12-17,15,24.110,DET,A,NYJ,True,...,0,0,0,0,0,0,0,0,0,0
495401,916,2002,200209080mia,2002-09-08,1,26.010,DET,A,MIA,False,...,0,0,0,0,0,0,0,0,0,0
495404,916,2002,200209290det,2002-09-29,4,26.031,DET,H,NOR,True,...,0,0,0,0,0,0,0,0,0,0
495406,916,2002,200210200det,2002-10-20,6,26.052,DET,H,CHI,True,...,0,0,0,0,0,0,0,0,0,0

In [24]:
offense_df.columns

Index(['player_id', 'year', 'game_id', 'date', 'game_number', 'age', 'team',
       'game_location', 'opponent', 'game_won', 'player_team_score',
       'opponent_score', 'passing_attempts', 'passing_completions',
       'passing_yards', 'passing_rating', 'passing_touchdowns',
       'passing_interceptions', 'passing_sacks', 'passing_sacks_yards_lost',
       'rushing_attempts', 'rushing_yards', 'rushing_touchdowns',
       'receiving_targets', 'receiving_receptions', 'receiving_yards',
       'receiving_touchdowns', 'kick_return_attempts', 'kick_return_yards',
       'kick_return_touchdowns', 'punt_return_attempts', 'punt_return_yards',
       'punt_return_touchdowns', 'defense_sacks', 'defense_tackles',
       'defense_tackle_assists', 'defense_interceptions',
       'defense_interception_yards', 'defense_interception_touchdowns',
       'defense_safeties', 'point_after_attemps', 'point_after_makes',
       'field_goal_attempts', 'field_goal_makes', 'punting_attempts',
       'punting_yards', 'punting_blocked'],
      dtype='object')

In [25]:
defense_columns = ['kick_return_attempts', 'kick_return_yards',
       'kick_return_touchdowns', 'punt_return_attempts', 'punt_return_yards',
       'punt_return_touchdowns', 'defense_sacks', 'defense_tackles',
       'defense_tackle_assists', 'defense_interceptions',
       'defense_interception_yards', 'defense_interception_touchdowns',
       'defense_safeties', 'punting_attempts',
       'punting_yards', 'punting_blocked']

In [26]:
offense_df = offense_df.drop(defense_columns, axis=1)

In [27]:
offense_df

,player_id,year,game_id,date,game_number,age,team,game_location,opponent,game_won,...,rushing_yards,rushing_touchdowns,receiving_targets,receiving_receptions,receiving_yards,receiving_touchdowns,point_after_attemps,point_after_makes,field_goal_attempts,field_goal_makes
0,4088,1992,199209130ram,1992-09-13,1,23.190,NWE,A,RAM,False,...,0,0,0,0,0,0,0,0,0,0
1,4088,1992,199209200nwe,1992-09-20,2,23.197,NWE,H,SEA,False,...,0,0,0,0,0,0,0,0,0,0
2,4088,1992,199209270nwe,1992-09-27,3,23.204,NWE,H,BUF,False,...,0,0,0,0,0,0,0,0,0,0
3,4088,1992,199210040nyj,1992-10-04,4,23.211,NWE,A,NYJ,False,...,0,0,0,0,0,0,0,0,0,0
4,4088,1992,199210110nwe,1992-10-11,5,23.218,NWE,H,SFO,False,...,4,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495385,916,2000,200011300min,2000-11-30,13,24.093,DET,A,MIN,False,...,0,0,0,0,0,0,0,0,0,0
495387,916,2000,200012170nyj,2000-12-17,15,24.110,DET,A,NYJ,True,...,0,0,0,0,0,0,0,0,0,0
495401,916,2002,200209080mia,2002-09-08,1,26.010,DET,A,MIA,False,...,0,0,0,0,0,0,0,0,0,0
495404,916,2002,200209290det,2002-09-29,4,26.031,DET,H,NOR,True,...,0,0,0,0,0,0,0,0,0,0
495406,916,2002,200210200det,2002-10-20,6,26.052,DET,H,CHI,True,...,0,0,0,0,0,0,0,0,0,0

In [28]:
offense_df.columns

Index(['player_id', 'year', 'game_id', 'date', 'game_number', 'age', 'team',
       'game_location', 'opponent', 'game_won', 'player_team_score',
       'opponent_score', 'passing_attempts', 'passing_completions',
       'passing_yards', 'passing_rating', 'passing_touchdowns',
       'passing_interceptions', 'passing_sacks', 'passing_sacks_yards_lost',
       'rushing_attempts', 'rushing_yards', 'rushing_touchdowns',
       'receiving_targets', 'receiving_receptions', 'receiving_yards',
       'receiving_touchdowns', 'point_after_attemps', 'point_after_makes',
       'field_goal_attempts', 'field_goal_makes'],
      dtype='object')

In [34]:
def score_calc(row):
    """Compute PPR score"""
    # starts from passing_yards, goes to field_goal_makes
    # we don't know how many yards they made the field goals from!!
    # weights_vec = np.array(0.04, 0, 4, -2, -0.1, 0, 0.1, 6, 0, 1, 0.1, 6, 0, 1, 3.4)
    ppr = 0
    ppr += 0.04 * row['passing_yards']
    ppr += 4 * row['passing_touchdowns']
    ppr += -2 * row['passing_interceptions']
    ppr += -0.1 * row['passing_sacks_yards_lost']
    ppr += 0.1 * row['rushing_yards']
    ppr += 6 * row['rushing_touchdowns']
    ppr += 1 * row['receiving_receptions']
    ppr += 0.1 * row['receiving_yards']
    ppr += 6 * row['receiving_touchdowns']
    ppr += 1 * row['point_after_makes']
    ppr += 3.4 * row['field_goal_makes']
    return ppr

In [35]:
offense_df.agg([score_calc])

KeyError: 'passing_yards'